version: 3

vars:
  VERSION: v0.0.1

tasks:
  test:
    cmds:
      - go test -v ./... -cover

  build:
    deps:
      - test
    cmds:
      - go build -v .

  install:
    deps:
      - build
    cmds:
      - go install -v

  uninstall:
    cmds:
      - rm -rf $(go env GOPATH)/bin/go-scaffold

  clean:
    cmds:
      - go clean

  validate:
    cmds:
      - go run . -i testdata/input.json -o testoutput testdata/template
      - tree testoutput

  docker_build:
    cmds:
      - docker build . -t forrestloomis786/go-scaffold:latest --target production
      - docker build . -t forrestloomis786/go-scaffold:{{.VERSION}} --target production
  
  push:
    deps:
      - docker_build
    cmds:
      - docker push forrestloomis786/go-scaffold:latest
      - docker push forrestloomis786/go-scaffold:{{.VERSION}}
